name: grocery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  image_picker: ^0.8.6
  loading_animation_widget: ^1.2.0+2
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.1
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_custom_clippers: ^2.0.0
  equatable: ^2.0.5
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_native_splash: ^2.2.9
  firebase_dynamic_links: ^4.3.11
  firebase_core: ^1.24.0
  multi_select_flutter: ^4.1.2
  flutter_colorpicker: ^1.0.3
  shimmer: ^2.0.0
  search_choices: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
#  flutter_native_splash: ^2.2.9
#  flutter_app_name: ^0.1.1

flutter_native_splash:
  image: assets/images/splash.png
  color: "#000000"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"

#flutter_app_name:
#  name: "Bilancia Web"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular Std Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf
    - family: Circular Std Medium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe UI.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
